- hosts: web
  become: true
  tasks:
   - name: create new deployment
     command: kubectl apply -f playbooks/deployement.yml 
   - name: create new service
     command: kubectl apply -f  playbooks/service.yml
