apiVersion: v1
kind: Service
metadata:
    name: aks-docker-jenkins-git-ansible
    labels:
       app: aks-docker-jenkins-git-ansible
spec:
  type: LoadBalancer
  ports:
    port: 8080
    targetPort: 80
    nodeport: 31200
  selector:
    app: aks-docker-jenkins-git-ansible
  type: LoadBalancer 
